---
title: "EDS Day 2 Activities"
author: "Michelle Lam"
date: "2022-08-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(palmerpenguins)
```

Find the derivative of $f(x)=x^2$ at x=3
```{r}
exp_1 <- expression(x^2)
deriv_1 <- deriv(exp_1, "x")
deriv_1
x <- 3
eval(deriv_1)
```

Find the derivative of $P(a)=2(3a+2)^4−5$ at a=1.2
```{r}
exp_2 <- expression(2 * (3 * a + 2)^4 - 5)
deriv_2 <- deriv(exp_2, "a")
deriv_2
a <- 1.2
eval(deriv_2)
```

Find the derivative of $g(t)=−4t/(t^2+1)^3$ at t=0
```{r}
exp_3 <- expression(-4 * t /(t^2 + 1)^ 3)
deriv_3 <- deriv(exp_3, "t")
deriv_3
t <- 0
eval(deriv_3)
```

Graph of Bill Length vs. Bill Depth
```{r}
ggplot(data = penguins, aes(x = bill_length_mm, y = bill_depth_mm)) +
  geom_point(aes(color = species)) +
  labs(x = "Bill Length (mm)", y = "Bill Depth (mm)", title = "Bill Length Vs Bill Depth") 
```

Graph of Flipper Length by Species (Jitterplot)
```{r}
ggplot(data = penguins, aes(x = species, y = flipper_length_mm)) +
  geom_jitter(aes(color = species)) +
  labs(x = "Penguin Species", y = "Flipper Length mm")
```

Graph of Flipper Length by Species (point)
```{r}
ggplot(data = penguins, aes(x = species, y = flipper_length_mm)) +
  geom_point(aes(color = species)) +
  labs(x = "Penguin Species", y = "Flipper Length mm")
```

